### ISSUE TITLE
Yaml anchor support for include yaml files

### ISSUE THREAD

**Issue by NoahFeinberg** [tanbro/pyyaml-include#33] opened 2023-04-21 17:27 UTC
Hi tanbro, I thought it would be nice if this library also supported anchors when including a yaml file so I wrote this PR https://github.com/tanbro/pyyaml-include/pull/32.

**Comment by tanbro** [comment] 2023-04-24 02:06
Duplicate of #32

**Closed** 2023-04-24 02:06 UTC
